# Generated by Django 3.0.6 on 2021-04-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ein',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
