# Generated by Django 3.0.6 on 2021-05-18 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_company_ein'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpress',
            name='press',
        ),
        migrations.AddField(
            model_name='userpress',
            name='description',
            field=models.CharField(default='Default press. Please change it', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpress',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='userpress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='press', to=settings.AUTH_USER_MODEL),
        ),
    ]
