# Generated by Django 3.0.6 on 2021-05-19 06:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210519_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryskill',
            name='primary_skill',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='secondaryskill',
            name='secondary_skill',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='toolandtechnology',
            name='tool_and_technology',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
