# Generated by Django 3.0.6 on 2021-05-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210519_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('CORPORATION', 'Corporation'), ('LLC', 'LLC'), ('LLP', 'LLP'), ('LP', 'LP'), ('NON-PROFIT', 'Non-Profit'), ('PARTNERSHIP', 'Partnership'), ('PUBLIC CORPORATION', 'Public Corporation'), ('SOLE PROPRIETORSHIP', 'Sole Proprietorship'), ('TRUST', 'Trust'), ('UNINCORPORATED ASSOCIATION', 'Unincorporated Association')], default='Corporation', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('PRODUCTION COMPANY', 'Production Company'), ('IN-HOUSE PRODUCTION COMPANY', 'In-house Production Company')], default='Production Company', max_length=255),
        ),
    ]
