# Generated by Django 3.0.6 on 2021-05-26 05:54

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210524_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_producer',
            },
        ),
    ]
