# Generated by Django 3.0.6 on 2021-05-26 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userproducer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('imported_from', models.CharField(default='manual', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imported_contact',
            },
        ),
    ]
