# Generated by Django 3.0.6 on 2021-06-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_usercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benjiaccount',
            name='email',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
