# Generated by Django 3.0.6 on 2021-06-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210604_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='is_personal',
            field=models.BooleanField(default=True),
        ),
    ]
