# Generated by Django 3.0.6 on 2021-08-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210723_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='benjiaccount',
            name='w9_s3_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
