# Generated by Django 3.0.6 on 2021-08-10 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_benjiaccount_w9_s3_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benjiaccount',
            name='w9_s3_url',
        ),
        migrations.CreateModel(
            name='GenericS3UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(default=0)),
                ('purpose', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 's3_documents',
            },
        ),
    ]
