# Generated by Django 3.0.6 on 2021-08-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210810_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generics3uploadedfile',
            name='path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='generics3uploadedfile',
            table='s3_document',
        ),
    ]
