# Generated by Django 3.0.6 on 2021-08-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210810_0626'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generics3uploadedfile',
            unique_together={('user', 'type', 'size', 'purpose', 'name')},
        ),
    ]
