# Generated by Django 3.0.6 on 2021-09-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210810_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='benjiaccount',
            name='tool_tip_step',
            field=models.IntegerField(default=0, help_text='the last tool tip step that the user has skipped'),
        ),
    ]
