# Generated by Django 3.0.6 on 2021-09-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_benjiaccount_tool_tip_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='benjiaccount',
            name='tool_tip_finished',
            field=models.BooleanField(default=False, help_text='whether the user has skipped all tool tips'),
        ),
    ]
