# Generated by Django 3.0.6 on 2021-10-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_companylogout'),
        ('user', '0018_benjiaccount_tool_tip_finished'),
    ]

    operations = [
    ]
