# Generated by Django 3.0.6 on 2021-10-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_benjiaccount_tool_tip_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='display_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='imported_from',
            field=models.CharField(choices=[('manual', 'Manual'), ('google', 'Google')], default='manual', max_length=32),
        ),
    ]
