# Generated by Django 3.0.6 on 2021-10-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_merge_20211005_1404'),
        ('user', '0019_auto_20211009_1017'),
    ]

    operations = [
    ]
