# Generated by Django 3.0.6 on 2021-10-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_merge_20211011_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='is_personal',
            field=models.BooleanField(default=True, help_text='whether belong to personal or company network'),
        ),
    ]
