# Generated by Django 3.0.6 on 2021-11-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20211023_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='benjiaccount',
            name='producer_tool_tip_finished',
            field=models.BooleanField(default=False, help_text="whether the user has skipped all tool tips on producer's screen"),
        ),
        migrations.AddField(
            model_name='benjiaccount',
            name='producer_tool_tip_step',
            field=models.IntegerField(default=0, help_text="the last tool tip step on producer's screen that the user has skipped"),
        ),
    ]
