# Generated by Django 3.0.6 on 2021-11-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20211102_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('PRODUCTION COMPANY', 'Production Company'), ('IN-HOUSE PRODUCTION COMPANY', 'In-house Production Company')], default='Production Company', max_length=255),
        ),
    ]
