# Generated by Django 3.0.6 on 2021-11-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20211124_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRODUCTION COMPANY', 'Production Company'), ('IN-HOUSE PRODUCTION COMPANY', 'In-house Production Company')], default='Production Company', max_length=255)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(blank=True, max_length=1024, null=True)),
                ('review', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'delete_company',
            },
        ),
        migrations.CreateModel(
            name='DeleteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1024, unique=True)),
                ('reason', models.CharField(choices=[(1, 'I_HAVE_DUPLICATE_ACCOUNT'), (2, 'GETTING_TO_MANY_MAILS'), (3, 'NOT_GETTING_ANY_VALUE_FOR_MY_MEMBERSHIP'), (4, 'PRIVACY_CONCERN'), (5, 'RECEIVING_UNWANTED_CONTACT'), (6, 'OTHER')], max_length=1024)),
                ('review', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'delete_user',
            },
        ),
    ]
