# Generated by Django 3.0.6 on 2021-12-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_deletecompany_deleteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybenjiaccountentry',
            name='relationship',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('CONTRACTOR', 'CONTRACTOR'), ('PRIVILEGED STAFF', 'PRIVILEGED STAFF'), ('COMMON STAFF', 'COMMON STAFF'), ('BUSINESS MEMBER', 'BUSINESS MEMBER')], default='OWNER', max_length=255),
        ),
    ]
