# Generated by Django 3.0.6 on 2021-12-23 13:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_deletecompany_deleteuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='headquarters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='year_founded',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CompanySpecialities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialities_company', to='user.Company')),
            ],
            options={
                'db_table': 'company_specialities',
            },
        ),
        migrations.CreateModel(
            name='CompanyPress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presses', to='user.Company')),
            ],
            options={
                'db_table': 'company_press',
            },
        ),
        migrations.CreateModel(
            name='CompanyPastClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_client', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='past_client_company', to='user.Company')),
            ],
            options={
                'db_table': 'company_past_client',
            },
        ),
        migrations.CreateModel(
            name='CompanyAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.CharField(blank=True, max_length=100, null=True)),
                ('award_year', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_company', to='user.Company')),
            ],
            options={
                'db_table': 'company_award',
            },
        ),
    ]
