# Generated by Django 3.0.6 on 2021-12-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20211223_1337'),
        ('user', '0025_auto_20211223_1227'),
    ]

    operations = [
    ]
