# Generated by Django 3.0.6 on 2022-01-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_merge_20211227_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontact',
            name='profile_photo_url',
            field=models.TextField(null=True),
        ),
    ]
