# Generated by Django 3.0.6 on 2022-01-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_usercontact_profile_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userheadline',
            name='headline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
