# Generated by Django 3.0.6 on 2022-01-15 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0028_auto_20220117_1412"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontact",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imported_contacts",
                to="user.Company",
            ),
        ),
        migrations.AlterField(
            model_name="usercontact",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imported_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
