# Generated by Django 3.0.6 on 2022-01-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20220115_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(default='Musical Groups and Artists', max_length=255),
        ),
        migrations.AlterField(
            model_name='deletecompany',
            name='type',
            field=models.CharField(default='Musical Groups and Artists', max_length=255),
        ),
    ]
