# Generated by Django 3.0.6 on 2022-02-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20220124_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='benjiaccount',
            name='primary_instrument',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
