# Generated by Django 3.0.6 on 2022-02-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_benjiaccount_primary_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benjiaccountactivationtoken',
            name='email',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner_email',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='email',
            field=models.CharField(max_length=1024),
        ),
    ]
