# Generated by Django 3.0.6 on 2022-02-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20220214_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccessrequesttoken',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Company'),
        ),
        migrations.AlterField(
            model_name='companybenjiaccountentry',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Company'),
        ),
    ]
