export const SET_WORKSPACE_COMPANY = 'SET_WORKSPACE_COMPANY';

export const FETCH_ACCOUNT_JOBS_REQUEST = 'FETCH_ACCOUNT_JOBS_REQUEST';
export const FETCH_ACCOUNT_JOBS_SUCCESS = 'FETCH_ACCOUNT_JOBS_SUCCESS';
export const FETCH_ACCOUNT_JOBS_FAIL = 'FETCH_ACCOUNT_JOBS_FAIL';

export const FETCH_ACCOUNT_CALLSHEETS_REQUEST = 'FETCH_ACCOUNT_CALLSHEETS_REQUEST';
export const FETCH_ACCOUNT_CALLSHEETS_SUCCESS = 'FETCH_ACCOUNT_CALLSHEETS_SUCCESS';
export const FETCH_ACCOUNT_CALLSHEETS_FAIL = 'FETCH_ACCOUNT_CALLSHEETS_FAIL';

export const FETCH_ACCOUNT_NETWORK_INVITATIONS_REQUEST = 'FETCH_ACCOUNT_NETWORK_INVITATIONS_REQUEST';
export const FETCH_ACCOUNT_NETWORK_INVITATIONS_SUCCESS = 'FETCH_ACCOUNT_NETWORK_INVITATIONS_SUCCESS';
export const FETCH_ACCOUNT_NETWORK_INVITATIONS_FAIL = 'FETCH_ACCOUNT_NETWORK_INVITATIONS_FAIL';
