# Generated by Django 3.0.6 on 2021-10-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnetwork',
            name='show_company',
            field=models.BooleanField(default=False),
        ),
    ]
