# Generated by Django 3.0.6 on 2022-01-15 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("personal_network", "0002_personalnetwork_show_company"),
    ]

    operations = [
        migrations.RenameModel("PersonalNetwork", "SocialNetwork"),
        migrations.AddField(
            model_name="socialnetwork",
            name="invitee_company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_network_invitee",
                to="user.Company",
            ),
        ),
        migrations.AddField(
            model_name="socialnetwork",
            name="invitor_company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_network_invitor",
                to="user.Company",
            ),
        ),
        migrations.AlterField(
            model_name="socialnetwork",
            name="invitee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_network_invitee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="socialnetwork",
            name="invitor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_network_invitor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="socialnetwork",
            unique_together={
                ("invitor_company", "invitee_company"),
                ("invitor", "invitee"),
                ("invitor_company", "invitee"),
                ("invitor", "invitee_company"),
            },
        ),
    ]
