import UserPic1 from '@iso/assets/images/user1.png';
import UserPic2 from '@iso/assets/images/user2.png';
import UserPic3 from '@iso/assets/images/user3.png';

export const sections = [
  {
    id: 1,
    title: 'Company Network',
    color: '#ffc06a',
    userItems: [
      {
        id: 1,
        name: 'Paul Amorese',
        value: 'Paul Amorese',
        label: 'Paul Amorese',
        avatar: UserPic1,
        role: 'Producer',
        type: 'cn',
      },
      {
        id: 2,
        name: 'Tarang Sachdev',
        value: 'Tarang Sachdev',
        label: 'Tarang Sachdev',
        avatar: UserPic3,
        role: 'Producer',
        type: 'cn',
      },
      {
        id: 3,
        name: 'Wang wei',
        value: 'Wang wei',
        label: 'Wang wei',
        avatar: UserPic2,
        role: 'Producer',
        type: 'cn',
      },
      {
        id: 4,
        name: 'Darshan Shah',
        value: 'Darshan Shah',
        label: 'Darshan Shah',
        avatar: UserPic2,
        role: 'Producer',
        type: 'cn',
      },
      {
        id: 5,
        name: 'Punit Patel',
        value: 'Punit Patel',
        label: 'Punit Patel',
        avatar: UserPic3,
        role: 'Producer',
        type: 'cn',
      },
      {
        id: 6,
        name: 'Rahul Patel',
        value: 'Rahul Patel',
        label: 'Rahul Patel',
        avatar: UserPic1,
        role: 'Producer',
        type: 'cn',
      },
      {
        id: 7,
        name: 'Shaym Bhai',
        value: 'Shaym Bhai',
        label: 'Shaym Bhai',
        avatar: UserPic2,
        role: 'Producer',
        type: 'cn',
      },
      {
        id: 8,
        name: 'Rakesh Karia',
        value: 'Rakesh Karia',
        label: 'Rakesh Karia',
        avatar: UserPic2,
        role: 'Producer',
        type: 'pn',
      },
      {
        id: 9,
        name: 'Jay Sachdev',
        value: 'Jay Sachdev',
        label: 'Jay Sachdev',
        avatar: UserPic3,
        role: 'Producer',
        type: 'pn',
      },
      {
        id: 10,
        name: 'Dipak Gohel',
        value: 'Dipak Gohel',
        label: 'Dipak Gohel',
        avatar: UserPic2,
        role: 'Producer',
        type: 'pn',
      },
      {
        id: 11,
        name: 'Prakash Patel',
        value: 'Prakash Patel',
        label: 'Prakash Patel',
        avatar: UserPic1,
        role: 'Producer',
        type: 'pn',
      },
      {
        id: 12,
        name: 'Mahesh Modi',
        value: 'Mahesh Modi',
        label: 'Mahesh Modi',
        avatar: UserPic2,
        role: 'Producer',
        type: 'pn',
      },
      {
        id: 13,
        name: 'Kishan Suchak',
        value: 'Kishan Suchak',
        label: 'Kishan Suchak',
        avatar: UserPic3,
        role: 'Producer',
        type: 'pn',
      },
      {
        id: 14,
        name: 'Keyur Modi',
        value: 'Keyur Modi',
        label: 'Keyur Modi',
        avatar: UserPic1,
        role: 'Producer',
        type: 'pn',
      },
      {
        id: 15,
        name: 'Dhruv Dobariya',
        value: 'Dhruv Dobariya',
        label: 'Dhruv Dobariya',
        avatar: UserPic1,
        role: 'Producer',
        type: 'cn',
      },
    ],
  },
  {
    id: 2,
    title: 'Personal Network',
    color: '#5c4da0',
    userItems: [
      {
        id: 1,
        name: 'Paul Amorese',
        value: 'Paul Amorese',
        label: 'Paul Amorese',
        avatar: UserPic3,
        role: 'Producer',
        type: 'cn',
      },
      {
        id: 2,
        name: 'Tarang Sachdev',
        value: 'Tarang Sachdev',
        label: 'Tarang Sachdev',
        avatar: UserPic2,
        role: 'Producer',
        type: 'cn',
      },
      {
        id: 3,
        name: 'Wang wei',
        value: 'Wang wei',
        label: 'Wang wei',
        avatar: UserPic2,
        role: 'Producer',
        type: 'cn',
      },
      {
        id: 4,
        name: 'Darshan Shah',
        value: 'Darshan Shah',
        label: 'Darshan Shah',
        avatar: UserPic1,
        role: 'Producer',
        type: 'cn',
      },
      {
        id: 5,
        name: 'Punit Patel',
        value: 'Punit Patel',
        label: 'Punit Patel',
        avatar: UserPic2,
        role: 'Producer',
        type: 'cn',
      },
      {
        id: 6,
        name: 'Rahul Patel',
        value: 'Rahul Patel',
        label: 'Rahul Patel',
        avatar: UserPic3,
        role: 'Producer',
        type: 'cn',
      },
      {
        id: 7,
        name: 'Shaym Bhai',
        value: 'Shaym Bhai',
        label: 'Shaym Bhai',
        avatar: UserPic2,
        role: 'Producer',
        type: 'cn',
      },
      {
        id: 8,
        name: 'Rakesh Karia',
        value: 'Rakesh Karia',
        label: 'Rakesh Karia',
        avatar: UserPic3,
        role: 'Producer',
        type: 'pn',
      },
      {
        id: 9,
        name: 'Jay Sachdev',
        value: 'Jay Sachdev',
        label: 'Jay Sachdev',
        avatar: UserPic1,
        role: 'Producer',
        type: 'pn',
      },
      {
        id: 10,
        name: 'Dipak Gohel',
        value: 'Dipak Gohel',
        label: 'Dipak Gohel',
        avatar: UserPic3,
        role: 'Producer',
        type: 'pn',
      },
      {
        id: 11,
        name: 'Prakash Patel',
        value: 'Prakash Patel',
        label: 'Prakash Patel',
        avatar: UserPic2,
        role: 'Producer',
        type: 'pn',
      },
      {
        id: 12,
        name: 'Mahesh Modi',
        value: 'Mahesh Modi',
        label: 'Mahesh Modi',
        avatar: UserPic3,
        role: 'Producer',
        type: 'pn',
      },
      {
        id: 13,
        name: 'Kishan Suchak',
        value: 'Kishan Suchak',
        label: 'Kishan Suchak',
        avatar: UserPic1,
        role: 'Producer',
        type: 'pn',
      },
      {
        id: 14,
        name: 'Keyur Modi',
        value: 'Keyur Modi',
        label: 'Keyur Modi',
        avatar: UserPic1,
        role: 'Producer',
        type: 'pn',
      },
      {
        id: 15,
        name: 'Dhruv Dobariya',
        value: 'Dhruv Dobariya',
        label: 'Dhruv Dobariya',
        avatar: UserPic2,
        role: 'Producer',
        type: 'cn',
      },
    ],
  },
];
