export const FETCH_JOB_CLIENT_REQUEST = 'FETCH_JOB_CLIENT_REQUEST';
export const FETCH_JOB_CLIENT_SUCCESS = 'FETCH_JOB_CLIENT_SUCCESS';
export const FETCH_JOB_CLIENT_FAIL = 'FETCH_JOB_CLIENT_FAIL';

export const CREATE_JOB_CLIENT_REQUEST = 'CREATE_JOB_CLIENT_REQUEST';
export const CREATE_JOB_CLIENT_SUCCESS = 'CREATE_JOB_CLIENT_SUCCESS';
export const CREATE_JOB_CLIENT_FAIL = 'CREATE_JOB_CLIENT_FAIL';

export const UPDATE_JOB_CLIENT_REQUEST = 'UPDATE_JOB_CLIENT_REQUEST';
export const UPDATE_JOB_CLIENT_SUCCESS = 'UPDATE_JOB_CLIENT_SUCCESS';
export const UPDATE_JOB_CLIENT_FAIL = 'UPDATE_JOB_CLIENT_FAIL';
