# Generated by Django 3.0.6 on 2021-06-27 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0002_auto_20210626_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='silacorporate',
            name='private_key',
            field=models.CharField(default='', help_text='User private key', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silauser',
            name='private_key',
            field=models.CharField(default='', help_text='User private key', max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='default', max_length=66)),
                ('private_key', models.TextField()),
                ('public_key', models.CharField(max_length=42)),
                ('registered_at_sila', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('sila_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='sila_adapter.SilaUser')),
            ],
            options={
                'unique_together': {('sila_user', 'nickname'), ('private_key', 'public_key')},
            },
        ),
        migrations.CreateModel(
            name='CorporateWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='default', max_length=66)),
                ('private_key', models.TextField()),
                ('public_key', models.CharField(max_length=42)),
                ('registered_at_sila', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('sila_corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='sila_adapter.SilaCorporate')),
            ],
            options={
                'unique_together': {('private_key', 'public_key'), ('sila_corporate', 'nickname')},
            },
        ),
    ]
