# Generated by Django 3.0.6 on 2021-07-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0004_auto_20210703_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silacorporate',
            name='private_key',
            field=models.CharField(help_text='User private key', max_length=100),
        ),
        migrations.AlterField(
            model_name='silauser',
            name='private_key',
            field=models.CharField(help_text='User private key', max_length=100),
        ),
    ]
