# Generated by Django 3.0.6 on 2021-07-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0005_auto_20210703_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='silacorporate',
            name='business_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='silacorporate',
            name='business_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='silacorporate',
            name='business_type',
            field=models.CharField(choices=[('CORPORATION', 'Corporation'), ('LLC', 'LLC'), ('LLP', 'LLP'), ('LP', 'LP'), ('NON-PROFIT', 'Non-Profit'), ('PARTNERSHIP', 'Partnership'), ('PUBLIC CORPORATION', 'Public Corporation'), ('SOLE PROPRIETORSHIP', 'Sole Proprietorship'), ('TRUST', 'Trust'), ('UNINCORPORATED ASSOCIATION', 'Unincorporated Association')], default='Corporation', max_length=255),
        ),
        migrations.AddField(
            model_name='silacorporate',
            name='category',
            field=models.CharField(choices=[('PRODUCTION COMPANY', 'Production Company'), ('IN-HOUSE PRODUCTION COMPANY', 'In-house Production Company')], default='Production Company', max_length=30),
        ),
        migrations.AddField(
            model_name='silacorporate',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='silacorporate',
            name='employer_id_number',
            field=models.CharField(default='', help_text='also known as EIN', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silacorporate',
            name='legal_company_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silacorporate',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='silacorporate',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='silacorporate',
            name='zip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
