# Generated by Django 3.0.6 on 2021-07-18 09:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0006_auto_20210704_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.CharField(help_text='A unique ID from Sila', max_length=100)),
                ('requested_at', models.DateTimeField()),
                ('sila_updated_at', models.DateTimeField()),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('passed', 'Passed'), ('pending', 'Pending'), ('review', 'Review'), ('failed', 'Failed'), ('member_unverified', 'Member Unverified'), ('member_failed', 'Member Failed'), ('member_review', 'Member Review'), ('member_pending', 'Member Pending'), ('documents_required', 'Documents Required'), ('documents_received', 'Documents Received'), ('webhook_pending', 'Webhook Pending')], max_length=25)),
                ('fail_reason', models.TextField(blank=True)),
                ('kyc_level', models.CharField(choices=[('DOC_KYC', 'Doc Kyc'), ('KYC-LITE', 'Kyc Lite'), ('RECEIVE_ONLY', 'Receive Only'), ('INSTANT-ACH', 'Instant Ach'), ('KYB-STANDARD', 'Kyb Standard'), ('KYB-LITE', 'Kyb Lite'), ('DEFAULT', 'Default')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='corporatewallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corporatewallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='silacorporate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silacorporate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='silauser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silauser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userwallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='KYC_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='A Unique Sila reference ID', max_length=100)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('passed', 'Passed'), ('pending', 'Pending'), ('review', 'Review'), ('failed', 'Failed'), ('member_unverified', 'Member Unverified'), ('member_failed', 'Member Failed'), ('member_review', 'Member Review'), ('member_pending', 'Member Pending'), ('documents_required', 'Documents Required'), ('documents_received', 'Documents Received'), ('webhook_pending', 'Webhook Pending')], max_length=25)),
                ('fail_reason', models.TextField(blank=True)),
                ('account_info_modified', models.BooleanField(default=False, help_text='Whether the info of SilaUser or SilaCorporate is modified')),
                ('entity_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sila_corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_requests', to='sila_adapter.SilaCorporate')),
                ('sila_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_requests', to='sila_adapter.SilaUser')),
            ],
        ),
    ]
