# Generated by Django 3.0.6 on 2021-07-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0007_auto_20210718_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc_history',
            name='fail_reason',
        ),
        migrations.RemoveField(
            model_name='kyc_request',
            name='fail_reason',
        ),
        migrations.AddField(
            model_name='kyc_history',
            name='kyc_request',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='kyc_histories', to='sila_adapter.KYC_Request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc_history',
            name='result_detail',
            field=models.TextField(blank=True, help_text='Show matched detail, unmatch detail, document required message'),
        ),
        migrations.AddField(
            model_name='kyc_request',
            name='result_detail',
            field=models.TextField(blank=True, help_text='Show matched detail, unmatch detail, document required message'),
        ),
    ]
