# Generated by Django 3.0.6 on 2021-07-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0008_auto_20210718_1536'),
        ('sila_adapter', '0007_auto_20210723_0759'),
    ]

    operations = [
    ]
