# Generated by Django 3.0.6 on 2021-07-31 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sila_adapter', '0009_merge_20210728_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidLinkedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=120)),
                ('routing_number', models.CharField(max_length=120)),
                ('account_name', models.CharField(max_length=120)),
                ('account_type', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=False)),
                ('account_status', models.CharField(max_length=120)),
                ('account_link_status', models.CharField(max_length=120)),
                ('match_score', models.FloatField(default=None)),
                ('entity_name', models.CharField(max_length=120)),
                ('account_owner_name', models.CharField(default=None, max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
