# Generated by Django 3.0.6 on 2021-07-31 14:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sila_adapter', '0011_auto_20210731_1440'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plaidlinkedaccount',
            unique_together={('user', 'account_number', 'account_name', 'account_type')},
        ),
    ]
