# Generated by Django 3.0.6 on 2021-07-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0012_auto_20210731_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatewallet',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
