# Generated by Django 3.0.6 on 2021-08-01 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sila_adapter', '0013_auto_20210731_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiatToSilaTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiat_withdrawls', to='sila_adapter.PlaidLinkedAccount')),
                ('from_wallet_corporate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiat_to_silas', to='sila_adapter.CorporateWallet')),
                ('from_wallet_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiat_to_silas', to='sila_adapter.UserWallet')),
            ],
        ),
        migrations.CreateModel(
            name='SilaToSilaTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('request_transaction_id', models.UUIDField()),
                ('is_auto_approve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiat_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_txs', to='sila_adapter.FiatToSilaTx')),
                ('from_wallet_corporate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_sila', to='sila_adapter.CorporateWallet')),
                ('from_wallet_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_sila', to='sila_adapter.UserWallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_sila', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
