# Generated by Django 3.0.6 on 2021-08-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0014_fiattosilatx_silatosilatx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silatosilatx',
            name='to_wallet',
        ),
        migrations.AddField(
            model_name='fiattosilatx',
            name='to_corporate_wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_silas_corporate', to='sila_adapter.CorporateWallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiattosilatx',
            name='to_user_wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_silas_corporate', to='sila_adapter.UserWallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silatosilatx',
            name='to_corporate_wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_silas_user', to='sila_adapter.CorporateWallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silatosilatx',
            name='to_user_wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_silas_user', to='sila_adapter.UserWallet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='silatosilatx',
            name='from_wallet_corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_silas', to='sila_adapter.CorporateWallet'),
        ),
        migrations.AlterField(
            model_name='silatosilatx',
            name='from_wallet_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_silas', to='sila_adapter.UserWallet'),
        ),
    ]
