# Generated by Django 3.0.6 on 2021-08-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0016_auto_20210803_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='public_key',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
