# Generated by Django 3.0.6 on 2021-08-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0018_auto_20210803_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silatosilatx',
            name='to_corporate_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_silas_user', to='sila_adapter.CorporateWallet', to_field='public_key'),
        ),
    ]
