# Generated by Django 3.0.6 on 2021-08-03 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0019_auto_20210803_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silatosilatx',
            name='from_wallet_corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_silas', to='sila_adapter.CorporateWallet', to_field='public_key'),
        ),
        migrations.AlterField(
            model_name='silatosilatx',
            name='from_wallet_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_silas', to='sila_adapter.UserWallet', to_field='public_key'),
        ),
        migrations.AlterField(
            model_name='silatosilatx',
            name='to_user_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_silas_user', to='sila_adapter.UserWallet', to_field='public_key'),
        ),
    ]
