# Generated by Django 3.0.6 on 2021-08-03 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0020_auto_20210803_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silatosilatx',
            name='request_transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='silatosilatx',
            name='to_corporate_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_silas_user', to='sila_adapter.CorporateWallet', to_field='public_key'),
        ),
        migrations.AlterField(
            model_name='silatosilatx',
            name='to_user_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_silas_user', to='sila_adapter.UserWallet', to_field='public_key'),
        ),
    ]
