# Generated by Django 3.0.6 on 2021-08-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0021_auto_20210803_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiattosilatx',
            name='request_transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiattosilatx',
            name='to_corporate_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_silas_corporate', to='sila_adapter.CorporateWallet'),
        ),
        migrations.AlterField(
            model_name='fiattosilatx',
            name='to_user_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_silas_corporate', to='sila_adapter.UserWallet'),
        ),
        migrations.AlterField(
            model_name='silatosilatx',
            name='from_wallet_corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_silas', to='sila_adapter.CorporateWallet'),
        ),
        migrations.AlterField(
            model_name='silatosilatx',
            name='from_wallet_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_silas', to='sila_adapter.UserWallet'),
        ),
        migrations.AlterField(
            model_name='silatosilatx',
            name='to_corporate_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_silas_user', to='sila_adapter.CorporateWallet'),
        ),
        migrations.AlterField(
            model_name='silatosilatx',
            name='to_user_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_silas_user', to='sila_adapter.UserWallet'),
        ),
    ]
