# Generated by Django 3.0.6 on 2021-08-03 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sila_adapter', '0022_auto_20210803_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiattosilatx',
            name='from_wallet_corporate',
        ),
        migrations.RemoveField(
            model_name='fiattosilatx',
            name='from_wallet_user',
        ),
        migrations.RemoveField(
            model_name='fiattosilatx',
            name='to_corporate_wallet',
        ),
        migrations.RemoveField(
            model_name='fiattosilatx',
            name='to_user_wallet',
        ),
        migrations.RemoveField(
            model_name='silatosilatx',
            name='from_wallet_corporate',
        ),
        migrations.RemoveField(
            model_name='silatosilatx',
            name='from_wallet_user',
        ),
        migrations.RemoveField(
            model_name='silatosilatx',
            name='to_corporate_wallet',
        ),
        migrations.RemoveField(
            model_name='silatosilatx',
            name='to_user_wallet',
        ),
        migrations.AddField(
            model_name='fiattosilatx',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fiattosilatx',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiat_txs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='silatosilatx',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
