# Generated by Django 3.0.6 on 2021-08-03 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0024_silatosilatx_to_sila_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='silatosilatx',
            name='from_sila_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_silas', to='sila_adapter.SilaUser'),
        ),
        migrations.AlterField(
            model_name='silatosilatx',
            name='to_sila_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_silas', to='sila_adapter.SilaUser'),
        ),
    ]
