# Generated by Django 3.0.6 on 2021-08-03 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sila_adapter', '0025_auto_20210803_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silatosilatx',
            name='from_sila_user',
        ),
        migrations.RemoveField(
            model_name='silatosilatx',
            name='to_sila_user',
        ),
        migrations.AddField(
            model_name='silatosilatx',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_silas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='silatosilatx',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_silas', to=settings.AUTH_USER_MODEL),
        ),
    ]
