# Generated by Django 3.0.6 on 2021-08-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0026_auto_20210803_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='silatosilatx',
            name='parent_request_transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
