# Generated by Django 3.0.6 on 2021-08-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0027_silatosilatx_parent_request_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='silacorporate',
            name='kyb_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='silauser',
            name='kyc_pass',
            field=models.BooleanField(default=False),
        ),
    ]
