# Generated by Django 3.0.6 on 2021-08-09 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_benjiaccount_w9_s3_url'),
        ('sila_adapter', '0028_auto_20210807_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiattosilatx',
            name='sila_status',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.CreateModel(
            name='PlaidLinkedCorporateAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=120)),
                ('routing_number', models.CharField(max_length=120)),
                ('account_name', models.CharField(max_length=120)),
                ('account_type', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=False)),
                ('account_status', models.CharField(max_length=120)),
                ('account_link_status', models.CharField(max_length=120)),
                ('match_score', models.FloatField(default=None, null=True)),
                ('entity_name', models.CharField(max_length=120)),
                ('account_owner_name', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_accounts', to='user.Company')),
            ],
            options={
                'unique_together': {('company', 'account_number', 'account_name', 'account_type')},
            },
        ),
    ]
