# Generated by Django 3.0.6 on 2021-08-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0029_auto_20210809_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilaCorporateMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('beneficial_owner', 'Beneficial Owner'), ('controlling_officer', 'Controlling Officer'), ('administrator', 'Administrator')], max_length=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sila_corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='sila_adapter.SilaCorporate')),
                ('sila_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sila_adapter.SilaUser')),
            ],
        ),
    ]
