# Generated by Django 3.0.6 on 2021-08-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0030_silacorporatemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiattosilatx',
            name='error_msg',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='fiattosilatx',
            name='note',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
