# Generated by Django 3.0.6 on 2021-08-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0031_auto_20210815_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='silatosilatx',
            name='error_msg',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='silatosilatx',
            name='note',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
