# Generated by Django 3.0.6 on 2021-08-16 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210810_0629'),
        ('sila_adapter', '0032_auto_20210815_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiattosilatx',
            name='to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_received_fiat_to_silas', to='user.Company'),
        ),
        migrations.AddField(
            model_name='silatosilatx',
            name='from_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_silas', to='user.Company'),
        ),
        migrations.AddField(
            model_name='silatosilatx',
            name='to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_silas', to='user.Company'),
        ),
    ]
