# Generated by Django 3.0.6 on 2021-08-18 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210810_0629'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sila_adapter', '0033_auto_20210816_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiattosilatx',
            old_name='account',
            new_name='account_user',
        ),
        migrations.CreateModel(
            name='SilaToFiatTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('request_transaction_id', models.UUIDField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('sila_status', models.CharField(default='unknown', max_length=40)),
                ('note', models.CharField(blank=True, max_length=512, null=True)),
                ('error_msg', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiat_sent', to='sila_adapter.PlaidLinkedAccount')),
                ('from_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_paid_fiat_to_silas', to='user.Company')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiat_txs_out', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
