# Generated by Django 3.0.6 on 2021-08-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0034_auto_20210818_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiattosilatx',
            name='account_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiat_withdrawls', to='sila_adapter.PlaidLinkedAccount'),
        ),
        migrations.AlterField(
            model_name='silatofiattx',
            name='account_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiat_sent', to='sila_adapter.PlaidLinkedAccount'),
        ),
    ]
