# Generated by Django 3.0.6 on 2021-08-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0035_auto_20210818_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiattosilatx',
            name='account_corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiat_withdrawls', to='sila_adapter.PlaidLinkedCorporateAccount'),
        ),
        migrations.AddField(
            model_name='silatofiattx',
            name='account_corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiat_sent', to='sila_adapter.PlaidLinkedCorporateAccount'),
        ),
    ]
