# Generated by Django 3.0.6 on 2021-09-10 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210810_0629'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sila_adapter', '0036_auto_20210818_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilaRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sila_requests', to='user.Company')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sila_requests', to=settings.AUTH_USER_MODEL)),
                ('sila_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sila_requested', to='sila_adapter.SilaUser')),
            ],
        ),
    ]
