# Generated by Django 3.0.6 on 2021-09-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0037_silarequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='silarequest',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
