# Generated by Django 3.0.6 on 2021-11-04 11:24

from django.db import migrations, models
from django.core.management import call_command


def load_bank_account_mapping_texture(apps, schema_editor):
    call_command(
        "loaddata", "apps/sila_adapter/fixtures/bank_account_mapping_texture.json"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0039_auto_20211015_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRoutinNumberMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(load_bank_account_mapping_texture),
    ]
