# Generated by Django 3.0.6 on 2021-11-08 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0040_bankroutinnumbermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='silarequest',
            name='sila_corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sila_corporate_requested', to='sila_adapter.SilaCorporate'),
        ),
        migrations.AlterField(
            model_name='silarequest',
            name='sila_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sila_requested', to='sila_adapter.SilaUser'),
        ),
    ]
