# Generated by Django 3.0.6 on 2021-11-24 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20211124_1509'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sila_adapter', '0041_auto_20211108_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='silacorporate',
            name='subcategory',
            field=models.CharField(choices=[('PRODUCTION COMPANY', 'Production Company'), ('IN-HOUSE PRODUCTION COMPANY', 'In-house Production Company')], default='Production Company', max_length=30),
        ),
        migrations.AlterField(
            model_name='silacorporate',
            name='category',
            field=models.CharField(choices=[('PRODUCTION COMPANY', 'Production Company'), ('IN-HOUSE PRODUCTION COMPANY', 'In-house Production Company')], default='Production Company', max_length=30),
        ),
        migrations.AlterField(
            model_name='silarequest',
            name='from_company',
            field=models.ForeignKey(blank=True, help_text='a company who is supposed to send money', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sila_requests', to='user.Company'),
        ),
        migrations.AlterField(
            model_name='silarequest',
            name='from_user',
            field=models.ForeignKey(blank=True, help_text='someone who is supposed to send money', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sila_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='silarequest',
            name='sila_corporate',
            field=models.ForeignKey(blank=True, help_text='a company who is supposed to receive money', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sila_corporate_requested', to='sila_adapter.SilaCorporate'),
        ),
        migrations.AlterField(
            model_name='silarequest',
            name='sila_user',
            field=models.ForeignKey(blank=True, help_text='someone who is supposed to receive money', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sila_requested', to='sila_adapter.SilaUser'),
        ),
        migrations.AlterField(
            model_name='silarequest',
            name='status',
            field=models.TextField(default='requested', help_text='either `requested` or `rejected`'),
        ),
    ]
