# Generated by Django 3.0.6 on 2021-11-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0042_auto_20211124_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silacorporate',
            name='subcategory',
        ),
    ]
