# Generated by Django 3.0.6 on 2021-11-22 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def initilize_requestee_status(apps, schema_editor):
    SilaRequest = apps.get_model("sila_adapter", "SilaRequest")
    SilaRequest.objects.filter(
        requester_status="requested"
    ).update(
        requestee_status="pending",
    )
    SilaRequest.objects.filter(
        requester_status="rejected"
    ).update(
        requestee_status="rejected",
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0022_auto_20211102_1317'),
        ('sila_adapter', '0043_remove_silacorporate_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='silarequest',
            old_name='status',
            new_name='requester_status'
        ),
        migrations.AlterField(
            model_name='silarequest',
            name='requester_status',
            field=models.TextField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('hidden', 'Hidden')], default='requested'),
        ),
        migrations.AddField(
            model_name='silarequest',
            name='requestee_status',
            field=models.TextField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('hidden', 'Hidden')], default='pending'),
        ),
        migrations.AddField(
            model_name='silarequest',
            name='revoke_reason',
            field=models.TextField(default=''),
        ),
        migrations.RunPython(initilize_requestee_status),
    ]
