# Generated by Django 3.0.6 on 2021-11-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0044_auto_20211122_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silarequest',
            name='show',
        ),
    ]
