# Generated by Django 3.0.6 on 2021-12-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0045_remove_silarequest_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='silacorporatemember',
            name='title',
            field=models.CharField(blank=True, help_text='Custom identifier within SilaCorporate', max_length=50),
        ),
    ]
