# Generated by Django 3.0.6 on 2021-12-03 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0046_silacorporatemember_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaidlinkedaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plaidlinkedaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plaidlinkedcorporateaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plaidlinkedcorporateaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PlaidLinkedAccountReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(help_text='A unique ID from Sila', max_length=100)),
                ('is_webhook_received', models.BooleanField(default=False, help_text='Whether a webhook is received')),
                ('initial_link_status', models.CharField(help_text='status from silasdk.User.linkAccount()', max_length=50)),
                ('initial_link_message', models.TextField(help_text='link message returned from silasdk.User.linkAccount()', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sila_corporate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaid_linked_references', to='sila_adapter.SilaCorporate')),
                ('sila_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaid_linked_references', to='sila_adapter.SilaUser')),
            ],
        ),
    ]
