# Generated by Django 3.0.6 on 2022-01-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0047_auto_20211203_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silauser',
            name='user_handle',
            field=models.CharField(help_text='Unique ID in Sila', max_length=100),
        ),
    ]
