# Generated by Django 3.0.6 on 2022-02-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0048_auto_20220130_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silacorporate',
            name='business_email',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='silauser',
            name='user_handle',
            field=models.CharField(help_text='Unique ID in Sila', max_length=100),
        ),
    ]
