# Generated by Django 3.0.6 on 2022-02-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0050_auto_20220214_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silacorporate',
            name='user_handle',
            field=models.CharField(help_text='Unique ID in Sila', max_length=100),
        ),
    ]
