export const FETCH_JOB_LOCATIONS_REQUEST = 'FETCH_JOB_LOCATIONS_REQUEST';
export const FETCH_JOB_LOCATIONS_SUCCESS = 'FETCH_JOB_LOCATIONS_SUCCESS';
export const FETCH_JOB_LOCATIONS_FAIL = 'FETCH_JOB_LOCATIONS_FAIL';

export const CREATE_JOB_LOCATION_REQUEST = 'CREATE_JOB_LOCATION_REQUEST';
export const CREATE_JOB_LOCATION_SUCCESS = 'CREATE_JOB_LOCATION_SUCCESS';
export const CREATE_JOB_LOCATION_FAIL = 'CREATE_JOB_LOCATION_FAIL';

export const UPDATE_JOB_LOCATION_REQUEST = 'UPDATE_JOB_LOCATION_REQUEST';
export const UPDATE_JOB_LOCATION_SUCCESS = 'UPDATE_JOB_LOCATION_SUCCESS';
export const UPDATE_JOB_LOCATION_FAIL = 'UPDATE_JOB_LOCATION_FAIL';

export const DELETE_JOB_LOCATION_REQUEST = 'DELETE_JOB_LOCATION_REQUEST';
export const DELETE_JOB_LOCATION_SUCCESS = 'DELETE_JOB_LOCATION_SUCCESS';
export const DELETE_JOB_LOCATION_FAIL = 'DELETE_JOB_LOCATION_FAIL';
