export const FETCH_JOB_EVENT_NOTE_GROUPS_REQUEST = 'FETCH_JOB_EVENT_NOTE_GROUPS_REQUEST';
export const FETCH_JOB_EVENT_NOTE_GROUPS_SUCCESS = 'FETCH_JOB_EVENT_NOTE_GROUPS_SUCCESS';
export const FETCH_JOB_EVENT_NOTE_GROUPS_FAIL = 'FETCH_JOB_EVENT_NOTE_GROUPS_FAIL';

export const FETCH_JOB_EVENT_NOTES_REQUEST = 'FETCH_JOB_EVENT_NOTES_REQUEST';
export const FETCH_JOB_EVENT_NOTES_SUCCESS = 'FETCH_JOB_EVENT_NOTES_SUCCESS';
export const FETCH_JOB_EVENT_NOTES_FAIL = 'FETCH_JOB_EVENT_NOTES_FAIL';

export const CREATE_JOB_EVENT_NOTE_REQUEST = 'CREATE_JOB_NOTE_EVENT_REQUEST';
export const CREATE_JOB_EVENT_NOTE_SUCCESS = 'CREATE_JOB_EVENT_NOTE_SUCCESS';
export const CREATE_JOB_EVENT_NOTE_FAIL = 'CREATE_JOB_EVENT_NOTE_FAIL';

export const UPDATE_EVENT_NOTE_REQUEST = 'UPDATE_EVENT_NOTE_REQUEST';
export const UPDATE_EVENT_NOTE_SUCCESS = 'UPDATE_EVENT_NOTE_SUCCESS';
export const UPDATE_EVENT_NOTE_FAIL = 'UPDATE_EVENT_NOTE_FAIL';

export const DELETE_EVENT_NOTE_REQUEST = 'DELETE_EVENT_NOTE_REQUEST';
export const DELETE_EVENT_NOTE_SUCCESS = 'DELETE_EVENT_NOTE_SUCCESS';
export const DELETE_EVENT_NOTE_FAIL = 'DELETE_EVENT_NOTE_FAIL';

export const ADD_EVENT_CREW_REQUEST = 'ADD_EVENT_CREW_REQUEST';
export const ADD_EVENT_CREW_SUCCESS = 'ADD_EVENT_CREW_SUCCESS';
export const ADD_EVENT_CREW_FAIL = 'ADD_EVENT_CREW_FAIL';

export const DELETE_EVENT_NOTE_IMAGE_REQUEST = 'DELETE_EVENT_NOTE_IMAGE_REQUEST';
export const DELETE_EVENT_NOTE_IMAGE_SUCCESS = 'DELETE_EVENT_NOTE_IMAGE_SUCCESS';
export const DELETE_EVENT_NOTE_IMAGE_FAIL = 'DELETE_EVENT_NOTE_IMAGE_FAIL';

