export const FETCH_CONTRACTOR_JOBS_REQUEST = 'FETCH_CONTRACTOR_JOBS_REQUEST';
export const FETCH_CONTRACTOR_JOBS_SUCCESS = 'FETCH_CONTRACTOR_JOBS_SUCCESS';
export const FETCH_CONTRACTOR_JOBS_FAIL = 'FETCH_CONTRACTOR_JOBS_FAIL';

export const FETCH_CONTRACTOR_JOB_DETAIL_REQUEST = 'FETCH_CONTRACTOR_JOB_DETAIL_REQUEST';
export const FETCH_CONTRACTOR_JOB_DETAIL_SUCCESS = 'FETCH_CONTRACTOR_JOB_DETAIL_SUCCESS';
export const FETCH_CONTRACTOR_JOB_DETAIL_FAIL = 'FETCH_CONTRACTOR_JOB_DETAIL_FAIL';

export const UPDATE_CONTRACTOR_JOB_REQUEST = 'UPDATE_CONTRACTOR_JOB_REQUEST';
export const UPDATE_CONTRACTOR_JOB_SUCCESS = 'UPDATE_CONTRACTOR_JOB_SUCCESS';
export const UPDATE_CONTRACTOR_JOB_FAIL = 'UPDATE_CONTRACTOR_JOB_FAIL';

export const ACCEPT_OR_DECLINE_JOB_REQUEST = 'ACCEPT_OR_DECLINE_JOB_REQUEST';
export const ACCEPT_OR_DECLINE_JOB_SUCCESS = 'ACCEPT_OR_DECLINE_JOB_SUCCESS';
export const ACCEPT_OR_DECLINE_JOB_FAIL = 'ACCEPT_OR_DECLINE_JOB_FAIL';

export const DELETE_BULK_CONTRACTOR_JOB_REQUEST = 'DELETE_BULK_CONTRACTOR_JOB_REQUEST';
export const DELETE_BULK_CONTRACTOR_JOB_SUCCESS = 'DELETE_BULK_CONTRACTOR_JOB_SUCCESS';
export const DELETE_BULK_CONTRACTOR_JOB_FAIL = 'DELETE_BULK_CONTRACTOR_JOB_FAIL';

export const CANCEL_JOB_REQUEST = 'CANCEL_JOB_REQUEST';
export const CANCEL_JOB_SUCCESS = 'CANCEL_JOB_SUCCESS';
export const CANCEL_JOB_FAIL = 'CANCEL_JOB_FAIL';