export const FETCH_JOB_CASTS_REQUEST = 'FETCH_JOB_CASTS_REQUEST';
export const FETCH_JOB_CASTS_SUCCESS = 'FETCH_JOB_CASTS_SUCCESS';
export const FETCH_JOB_CASTS_FAIL = 'FETCH_JOB_CASTS_FAIL';

export const CREATE_JOB_CAST_REQUEST = 'CREATE_JOB_CAST_REQUEST';
export const CREATE_JOB_CAST_SUCCESS = 'CREATE_JOB_CAST_SUCCESS';
export const CREATE_JOB_CAST_FAIL = 'CREATE_JOB_CAST_FAIL';

export const UPDATE_JOB_CAST_REQUEST = 'UPDATE_JOB_CAST_REQUEST';
export const UPDATE_JOB_CAST_SUCCESS = 'UPDATE_JOB_CAST_SUCCESS';
export const UPDATE_JOB_CAST_FAIL = 'UPDATE_JOB_CAST_FAIL';

export const DELETE_JOB_CAST_REQUEST = 'DELETE_JOB_CAST_REQUEST';
export const DELETE_JOB_CAST_SUCCESS = 'DELETE_JOB_CAST_SUCCESS';
export const DELETE_JOB_CAST_FAIL = 'DELETE_JOB_CAST_FAIL';

export const CREATE_CAST_WARDROBE_REQUEST = 'CREATE_CAST_WARDROBE_REQUEST';
export const CREATE_CAST_WARDROBE_SUCCESS = 'CREATE_CAST_WARDROBE_SUCCESS';
export const CREATE_CAST_WARDROBE_FAIL = 'CREATE_CAST_WARDROBE_FAIL';

export const UPDATE_CAST_WARDROBE_REQUEST = 'UPDATE_CAST_WARDROBE_REQUEST';
export const UPDATE_CAST_WARDROBE_SUCCESS = 'UPDATE_CAST_WARDROBE_SUCCESS';
export const UPDATE_CAST_WARDROBE_FAIL = 'UPDATE_CAST_WARDROBE_FAIL';

export const DELETE_CAST_WARDROBE_REQUEST = 'DELETE_CAST_WARDROBE_REQUEST';
export const DELETE_CAST_WARDROBE_SUCCESS = 'DELETE_CAST_WARDROBE_SUCCESS';
export const DELETE_CAST_WARDROBE_FAIL = 'DELETE_CAST_WARDROBE_FAIL';
