# Generated by Django 3.0.6 on 2021-03-19 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=255)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('payment_due', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('In Dispute', 'In Dispute'), ('Approved', 'Approved'), ('Received', 'Received'), ('Payment Sent', 'Payment Sent')], default='Requested', max_length=30)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.BooleanField(default=False)),
                ('benji_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('document', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_due', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='finance.Invoice')),
            ],
            options={
                'db_table': 'invoice_receipt',
            },
        ),
        migrations.CreateModel(
            name='InvoiceMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('price_type', models.CharField(choices=[('HOURLY', 'HOURLY'), ('FIXED', 'FIXED')], default='FIXED', max_length=30)),
                ('daily_hours', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('working_days', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('working_rate', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('kit_fee', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('project_rate', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('job_memo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobMemo')),
            ],
            options={
                'db_table': 'invoice_memo',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('units', models.PositiveIntegerField()),
                ('number_of_days', models.PositiveIntegerField()),
                ('rate', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.Invoice')),
            ],
            options={
                'db_table': 'invoice_line_item',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('document', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.Invoice')),
            ],
            options={
                'db_table': 'invoice_uploaded_document',
            },
        ),
        migrations.CreateModel(
            name='InvoiceBillTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_to', to='finance.Invoice')),
            ],
            options={
                'db_table': 'invoice_bill_to',
            },
        ),
        migrations.CreateModel(
            name='InvoiceBillFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_from', to='finance.Invoice')),
            ],
            options={
                'db_table': 'invoice_bill_from',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_memo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finance.InvoiceMemo'),
        ),
    ]
