# Generated by Django 3.0.6 on 2021-04-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210402_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebillfrom',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoicebillto',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
