# Generated by Django 3.0.6 on 2021-07-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20210618_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('In Dispute', 'In Dispute'), ('Approved', 'Approved'), ('Received', 'Received'), ('Payment processing', 'Payment processing'), ('Payment archive', 'Payment archive'), ('Payment overdue', 'Payment overdue'), ('Payment Sent', 'Payment Sent')], default='Requested', max_length=30),
        ),
    ]
