# Generated by Django 3.0.6 on 2021-07-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20210723_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='job_name',
            field=models.CharField(default='JobX', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='job_number',
            field=models.CharField(default='JobX', max_length=255),
            preserve_default=False,
        ),
    ]
