# Generated by Django 3.0.6 on 2021-09-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20210726_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='agency_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
