# Generated by Django 3.0.6 on 2021-12-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20210907_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('In Dispute', 'In Dispute'), ('Approved', 'Approved'), ('Received', 'Received'), ('Payment archive', 'Payment archive'), ('Payment overdue', 'Payment overdue')], default='Requested', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Paid', 'Paid'), ('Failed', 'Failed')], max_length=30, null=True),
        ),
    ]
