# Generated by Django 3.0.6 on 2021-12-21 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sila_adapter', '0047_auto_20211203_1449'),
        ('finance', '0010_auto_20211201_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='sila_adapter.SilaToSilaTx'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_due',
            field=models.DateField(),
        ),
    ]
