# Generated by Django 3.0.6 on 2022-02-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_invoice_status_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebillfrom',
            name='email',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='invoicebillto',
            name='email',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
