# Generated by Django 3.0.6 on 2022-02-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20220214_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicememo',
            name='daily_hours',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
