export const FETCH_JOB_SCRIPTS_REQUEST = 'FETCH_JOB_SCRIPTS_REQUEST';
export const FETCH_JOB_SCRIPTS_SUCCESS = 'FETCH_JOB_SCRIPTS_SUCCESS';
export const FETCH_JOB_SCRIPTS_FAIL = 'FETCH_JOB_SCRIPTS_FAIL';

export const CREATE_JOB_SCRIPT_REQUEST = 'CREATE_JOB_SCRIPT_REQUEST';
export const CREATE_JOB_SCRIPT_SUCCESS = 'CREATE_JOB_SCRIPT_SUCCESS';
export const CREATE_JOB_SCRIPT_FAIL = 'CREATE_JOB_SCRIPT_FAIL';

export const UPDATE_JOB_SCRIPT_REQUEST = 'UPDATE_JOB_SCRIPT_REQUEST';
export const UPDATE_JOB_SCRIPT_SUCCESS = 'UPDATE_JOB_SCRIPT_SUCCESS';
export const UPDATE_JOB_SCRIPT_FAIL = 'UPDATE_JOB_SCRIPT_FAIL';

export const DELETE_JOB_SCRIPT_REQUEST = 'DELETE_JOB_SCRIPT_REQUEST';
export const DELETE_JOB_SCRIPT_SUCCESS = 'DELETE_JOB_SCRIPT_SUCCESS';
export const DELETE_JOB_SCRIPT_FAIL = 'DELETE_JOB_SCRIPT_FAIL';
