export const FETCH_JOB_SHOOT_NOTES_REQUEST = 'FETCH_JOB_SHOOT_NOTES_REQUEST';
export const FETCH_JOB_SHOOT_NOTES_SUCCESS = 'FETCH_JOB_SHOOT_NOTES_SUCCESS';
export const FETCH_JOB_SHOOT_NOTES_FAIL = 'FETCH_JOB_SHOOT_NOTES_FAIL';

export const CREATE_JOB_SHOOT_NOTE_REQUEST = 'CREATE_JOB_SHOOT_NOTE_REQUEST';
export const CREATE_JOB_SHOOT_NOTE_SUCCESS = 'CREATE_JOB_SHOOT_NOTE_SUCCESS';
export const CREATE_JOB_SHOOT_NOTE_FAIL = 'CREATE_JOB_SHOOT_NOTE_FAIL';

export const UPDATE_SHOOT_NOTE_REQUEST = 'UPDATE_SHOOT_NOTE_REQUEST';
export const UPDATE_SHOOT_NOTE_SUCCESS = 'UPDATE_SHOOT_NOTE_SUCCESS';
export const UPDATE_SHOOT_NOTE_FAIL = 'UPDATE_SHOOT_NOTE_FAIL';

export const DELETE_SHOOT_NOTE_REQUEST = 'DELETE_SHOOT_NOTE_REQUEST';
export const DELETE_SHOOT_NOTE_SUCCESS = 'DELETE_SHOOT_NOTE_SUCCESS';
export const DELETE_SHOOT_NOTE_FAIL = 'DELETE_SHOOT_NOTE_FAIL';

export const DELETE_SHOOT_NOTE_IMAGE_REQUEST = 'DELETE_SHOOT_NOTE_IMAGE_REQUEST';
export const DELETE_SHOOT_NOTE_IMAGE_SUCCESS = 'DELETE_SHOOT_NOTE_IMAGE_SUCCESS';
export const DELETE_SHOOT_NOTE_IMAGE_FAIL = 'DELETE_SHOOT_NOTE_IMAGE_FAIL';
