from django.urls import include, path

from apps.jobs.view.crew import (BookCrewViewSet, JobMemoAcceptDeclineViewSet, JobMemoViewSet, ReplaceMemoViewSet,
                                 VirtualMemoViewSet, retrieve_all_departments_in_a_job,
                                 retrieve_all_job_roles_in_a_department,
                                 retrieve_crews_accepted_memo_in_a_job, retrieve_full_view_memos_in_a_job,
                                 retrieve_job_memo_and_job, retrieve_job_memos_in_a_job, retrieve_job_memos_in_a_user,
                                 validate_memo_invitation_token, remove_job_memo_attachment, CancelBookedJobMemoViewSet)

v1_urlpatterns = [
    # Job Memo
    path("job/<int:job_id>/job_memo/",
         JobMemoViewSet.as_view({"post": "create"}),
         name="job-memo"),
    path("job_memo/<int:pk>/",
         JobMemoViewSet.as_view({"put": "update", "delete": "destroy", "get": "retrieve",
                                 "patch": "partial_update"}),
         name="job-memo-detail"),
    path("job_memo/bulk_delete/",
         JobMemoViewSet.as_view({"post": "bulk_delete"}),
         name="job-memo-bulk-delete"),
    path("job_memo/<int:pk>/cancel/",
         JobMemoViewSet.as_view({"post": "cancel_memo"}),
         name="job-memo-cancel"),
    path("job_memo/<int:pk>/update_hold/",
         JobMemoViewSet.as_view({"post": "update_hold"}),
         name="job-memo-update-hold"),
    path("job_memo/<int:pk>/accept_decline/",
         JobMemoAcceptDeclineViewSet.as_view({"post": "create"}),
         name="job-memo-accept-decline"),
    path("job_memo/<int:pk>/cancel_booked_memo/",
         CancelBookedJobMemoViewSet.as_view({"post": "cancel_booked_memo"}),
         name="cancel-booked-memo"),
    path("job_memo/<int:pk>/delete_booked_memo/",
         CancelBookedJobMemoViewSet.as_view({"delete": "delete_booked_memo"}),
         name="delete-booked-memo"),
    path("job_memo/<int:pk>/update_headline/",
         JobMemoViewSet.as_view({"patch": "update_headline"}),
         name="job-memo-update-headline"),
    path("job_memo/<int:pk>/update_rates/",
         JobMemoViewSet.as_view({"patch": "update_rates"}),
         name="job-memo-update-rates"),
    # Virtual Memo
    # Virtual Memo
    path("job/<int:job_id>/virtual_memo/",
         VirtualMemoViewSet.as_view({"post": "create", "get": "list"}),
         name="virtual-memo"),
    path("virtual_memo/<int:pk>/",
         VirtualMemoViewSet.as_view({"put": "update", "delete": "destroy", "get": "retrieve",
                                     "patch": "partial_update"}),
         name="virtual-memo-detail"),
    path("job/<int:job_id>/replace_memo/",
         ReplaceMemoViewSet.as_view({"post": "replace_memo"}),
         name="replace-memo"),
    # Special APIs
    path("job/<int:job_id>/job_role_groups/",
         retrieve_all_departments_in_a_job,
         name="retrieve-all-departments-in-a-job"),
    path("job_role_group/<int:job_role_group_id>/job_roles/",
         retrieve_all_job_roles_in_a_department,
         name="retrieve-all-job-roles-in-a-department"),
    # path("job/<int:job_id>/contractors/<str:filter>/",
    #      retrieve_contractors_by_filter_in_a_job,
    #      name="retrieve-contractors-by-filter-in-a-job"),
    path("job/<int:job_id>/job_memos/",
         retrieve_job_memos_in_a_job,
         name="retrieve-job-memos-in-a-job"),
    path("job/<int:job_id>/job_memos/<int:job_memo_id>/attachments/<int:attachment_id>/",
         remove_job_memo_attachment,
         name="remove-job-memo-attachment"),
    path("user/<int:user_id>/job_memos/",
         retrieve_job_memos_in_a_user,
         name="retrieve-job-memos-in-a-user"),
    path("job_memo/<int:job_memo_id>/detail/",
         retrieve_job_memo_and_job,
         name="retrieve-job-memo-and-job"),
    path("job/<int:job_id>/full_view/",
         retrieve_full_view_memos_in_a_job,
         name="retrieve-full-view-memos-in-a-job"),
    path("job/<int:job_id>/crews/",
         retrieve_crews_accepted_memo_in_a_job,
         name="retrieve-crews-accepted-memo-in-a-job"),
    path("validate_memo_invitation_token/",
         validate_memo_invitation_token,
         name="validate-memo-invitation-token"),
    # Book Crew API
    path("book_crew/<int:job_id>/",
         BookCrewViewSet.as_view({"post": "create"}),
         name="book-crew"),

]

urlpatterns = [
    path("", include(v1_urlpatterns)),
]
