export const FETCH_PRODUCTION_CONTACTS_REQUEST = 'FETCH_PRODUCTION_CONTACTS_REQUEST ';
export const FETCH_PRODUCTION_CONTACTS_SUCCESS = 'FETCH_PRODUCTION_CONTACTS_SUCCESS ';
export const FETCH_PRODUCTION_CONTACTS_FAIL = 'FETCH_PRODUCTION_CONTACTS_FAIL ';

export const FETCH_CREWS_REQUEST = 'FETCH_CREWS_REQUEST';
export const FETCH_CREWS_SUCCESS = 'FETCH_CREWS_SUCCESS';
export const FETCH_CREWS_FAIL = 'FETCH_CREWS_FAIL';

export const FETCH_FULLVIEW_REQUEST = 'FETCH_FULLVIEW_REQUEST';
export const FETCH_FULLVIEW_SUCCESS = 'FETCH_FULLVIEW_SUCCESS';
export const FETCH_FULLVIEW_FAIL = 'FETCH_FULLVIEW_FAIL';

export const FETCH_PRINT_VIEW_REQUEST = 'FETCH_PRINT_VIEW_REQUEST';
export const FETCH_PRINT_VIEW_SUCCESS = 'FETCH_PRINT_VIEW_SUCCESS';
export const FETCH_PRINT_VIEW_FAIL = 'FETCH_PRINT_VIEW_FAIL';

export const CREATE_CALLSHEET_REQUEST = 'CREATE_CALLSHEET_REQUEST';
export const CREATE_CALLSHEET_SUCCESS = 'CREATE_CALLSHEET_SUCCESS';
export const CREATE_CALLSHEET_FAIL = 'CREATE_CALLSHEET_FAIL';

export const DELETE_CALLSHEET_REQUEST = 'DELETE_CALLSHEET_REQUEST';
export const DELETE_CALLSHEET_SUCCESS = 'DELETE_CALLSHEET_SUCCESS';
export const DELETE_CALLSHEET_FAIL = 'DELETE_CALLSHEET_FAIL';

export const DELETE_BULK_CALLSHEET_REQUEST = 'DELETE_BULK_CALLSHEET_REQUEST';
export const DELETE_BULK_CALLSHEET_SUCCESS = 'DELETE_BULK_CALLSHEET_SUCCESS';
export const DELETE_BULK_CALLSHEET_FAIL = 'DELETE_BULK_CALLSHEET_FAIL';

export const UPDATE_CALLSHEET_REQUEST = 'UPDATE_CALLSHEET_REQUEST';
export const UPDATE_CALLSHEET_SUCCESS = 'UPDATE_CALLSHEET_SUCCESS';
export const UPDATE_CALLSHEET_FAIL = 'UPDATE_CALLSHEET_FAIL';

export const SEND_CALLSHEET_REQUEST = 'SEND_CALLSHEET_REQUEST';
export const SEND_CALLSHEET_SUCCESS = 'SEND_CALLSHEET_SUCCESS';
export const SEND_CALLSHEET_FAIL = 'SEND_CALLSHEET_FAIL';

export const FETCH_CALLSHEET_DATES_REQUEST = 'FETCH_CALLSHEET_DATES_REQUEST';
export const FETCH_CALLSHEET_DATES_SUCCESS = 'FETCH_CALLSHEET_DATES_SUCCESS';
export const FETCH_CALLSHEET_DATES_FAIL = 'FETCH_CALLSHEET_DATES_FAIL';

export const FETCH_USER_CALLSHEETS_REQUEST = 'FETCH_USER_CALLSHEETS_REQUEST';
export const FETCH_USER_CALLSHEETS_SUCCESS = 'FETCH_USER_CALLSHEETS_SUCCESS';
export const FETCH_USER_CALLSHEETS_FAIL = 'FETCH_USER_CALLSHEETS_FAIL';

export const FETCH_CALLSHEET_DETAIL_REQUEST = 'FETCH_CALLSHEET_DETAIL_REQUEST';
export const FETCH_CALLSHEET_DETAIL_SUCCESS = 'FETCH_CALLSHEET_DETAIL_SUCCESS';
export const FETCH_CALLSHEET_DETAIL_FAIL = 'FETCH_CALLSHEET_DETAIL_FAIL';

export const ACCEPT_CALLSHEET_REQUEST = 'ACCEPT_CALLSHEET_REQUEST';
export const ACCEPT_CALLSHEET_SUCCESS = 'ACCEPT_CALLSHEET_SUCCESS';
export const ACCEPT_CALLSHEET_FAIL = 'ACCEPT_CALLSHEET_FAIL'

export const SET_CALLSHEET_FORM = 'SET_CALLSHEET_FORM';