export const FETCH_JOB_EVENTS_REQUEST = 'FETCH_JOB_EVENTS_REQUEST';
export const FETCH_JOB_EVENTS_SUCCESS = 'FETCH_JOB_EVENTS_SUCCESS';
export const FETCH_JOB_EVENTS_FAIL = 'FETCH_JOB_EVENTS_FAIL';

export const CREATE_JOB_EVENT_REQUEST = 'CREATE_JOB_EVENT_REQUEST';
export const CREATE_JOB_EVENT_SUCCESS = 'CREATE_JOB_EVENT_SUCCESS';
export const CREATE_JOB_EVENT_FAIL = 'CREATE_JOB_EVENT_FAIL';

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL';

export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL';

