export const SET_CALENDAR_VIEW = 'SET_CALENDAR_VIEW';
export const SET_SCHEDULE_VIEW = 'SET_SCHEDULE_VIEW';
export const SET_CALENDAR_DATE = 'SET_CALENDAR_DATE';
export const SET_SCHEDULE_FILTER = 'SET_SCHEDULE_FILTER';



