# Generated by Django 3.0.6 on 2021-03-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMemoAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(default=0)),
                ('job_memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobMemo')),
            ],
            options={
                'db_table': 'job_memo_attachment',
            },
        ),
    ]
