# Generated by Django 3.0.6 on 2021-03-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobmemoattachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmemoattachment',
            old_name='title',
            new_name='name',
        ),
    ]
