# Generated by Django 3.0.6 on 2021-03-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210322_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmemoattachment',
            name='type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
