# Generated by Django 3.0.6 on 2021-03-26 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_auto_20210322_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmemo',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_job_memo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobmemo',
            name='agency_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobmemo',
            name='agency_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
