# Generated by Django 3.0.6 on 2021-03-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20210326_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMemoHeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(blank=True)),
                ('job_memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobMemo')),
            ],
            options={
                'db_table': 'job_memo_headline',
            },
        ),
    ]
