# Generated by Django 3.0.6 on 2021-03-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobmemoheadline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobMemoHeadline',
        ),
    ]
