# Generated by Django 3.0.6 on 2021-03-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_delete_jobmemoheadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmemo',
            name='headline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
