# Generated by Django 3.0.6 on 2021-06-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_jobrolegroup_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMemoRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number_of_days', models.PositiveIntegerField(default=1)),
                ('day_rate', models.FloatField(default=0.0)),
                ('project_rate', models.FloatField(default=0.0)),
                ('job_memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='jobs.JobMemo')),
            ],
            options={
                'db_table': 'job_memo_rate',
            },
        ),
    ]
