# Generated by Django 3.0.6 on 2021-06-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_jobmemorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmemorate',
            name='price_type',
            field=models.CharField(default='FIXED', max_length=20),
        ),
    ]
