# Generated by Django 3.0.6 on 2021-06-25 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20210618_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmemoshootdate',
            name='job_memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoot_dates', to='jobs.JobMemo'),
        ),
        migrations.AlterField(
            model_name='jobrolegroup',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_role_groups', to='jobs.Job'),
        ),
    ]
