# Generated by Django 3.0.6 on 2021-08-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20210625_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmemo',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_memos', to='jobs.Job'),
        ),
    ]
