# Generated by Django 3.0.6 on 2021-10-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20211023_0908'),
        ('jobs', '0016_jobmemo_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('company', 'title'), ('company', 'job_number')},
        ),
    ]
