# Generated by Django 3.0.6 on 2021-11-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_job_wrap_and_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='paid_by',
            field=models.CharField(blank=True, choices=[('bank', 'bank'), ('wallet', 'wallet')], max_length=32, null=True),
        ),
    ]
