# Generated by Django 3.0.6 on 2021-12-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_job_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE'), ('WRAPPED', 'WRAPPED')], default='PENDING', max_length=255),
        ),
    ]
