# Generated by Django 3.0.6 on 2021-12-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_auto_20211212_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmemo',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
