# Generated by Django 3.0.6 on 2022-01-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_jobmemo_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='set_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='sound_check_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='venue',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
