# Generated by Django 3.0.6 on 2022-01-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_auto_20220110_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='venue',
        ),
    ]
