# Generated by Django 3.0.6 on 2022-01-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20220117_1412'),
        ('jobs', '0026_remove_job_venue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('company', 'title')},
        ),
    ]
