# Generated by Django 3.0.6 on 2022-02-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_auto_20220120_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='wrap_and_pay_type',
            field=models.IntegerField(blank=True, choices=[(1, 'PAY_WITHOUT_INVOICING'), (2, 'PAY_WITH_INVOICING')], null=True),
        ),
    ]
