# Generated by Django 3.0.6 on 2022-02-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_auto_20220211_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmemo',
            name='agency_email',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='jobmemo',
            name='email',
            field=models.CharField(max_length=1024),
        ),
    ]
