# Generated by Django 3.0.6 on 2022-02-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_auto_20220216_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='set_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='sound_check_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
