export const SET_CONTRACTOR_CALENDAR_VIEW = 'SET_CONTRACTOR_CALENDAR_VIEW';
export const SET_CONTRACTOR_SCHEDULE_VIEW = 'SET_CONTRACTOR_SCHEDULE_VIEW';
export const SET_CONTRACTOR_CALENDAR_DATE = 'SET_CONTRACTOR_CALENDAR_DATE';

export const FETCH_CONTRACTOR_EVENT_NOTE_REQUEST = 'FETCH_CONTRACTOR_EVENT_NOTE_REQUEST';
export const FETCH_CONTRACTOR_EVENT_NOTE_SUCCESS = 'FETCH_CONTRACTOR_EVENT_NOTE_SUCCESS';
export const FETCH_CONTRACTOR_EVENT_NOTE_FAIL = 'FETCH_CONTRACTOR_EVENT_NOTE_FAIL';

export const FETCH_CONTRACTOR_SHOOT_NOTE_REQUEST = 'FETCH_CONTRACTOR_SHOOT_NOTE_REQUEST';
export const FETCH_CONTRACTOR_SHOOT_NOTE_SUCCESS = 'FETCH_CONTRACTOR_SHOOT_NOTE_SUCCESS';
export const FETCH_CONTRACTOR_SHOOT_NOTE_FAIL = 'FETCH_CONTRACTOR_SHOOT_NOTE_FAIL';

export const FETCH_CONTRACTOR_HOLD_MEMO_REQUEST = 'FETCH_CONTRACTOR_HOLD_MEMO_REQUEST';
export const FETCH_CONTRACTOR_HOLD_MEMO_SUCCESS = 'FETCH_CONTRACTOR_HOLD_MEMO_SUCCESS';
export const FETCH_CONTRACTOR_HOLD_MEMO_FAIL = 'FETCH_CONTRACTOR_HOLD_MEMO_FAIL';
