from django.urls import include, path

from apps.finance.views import (CompanyInvoiceViewSet, ContractorInvoiceViewSet, InvoiceBillFromViewSet,
                                InvoiceBillToViewSet, InvoiceDocumentViewSet, InvoiceLineItemViewSet,
                                InvoiceReceiptViewSet, InvoiceViewSet, InvoicePdf, PreviewReport, PayFromBuddi,
                                PayFromBank)

v1_urlpatterns = [
    # Company Finance
    path("invoice/pdf/<int:pk>/", InvoicePdf.as_view()),
    path("job/<int:job_id>/job_memo/<int:job_memo_id>/invoice_memo/",
         CompanyInvoiceViewSet.as_view({"post": "create"}),
         name="invoice-memo"),
    path("invoice_memo/<int:pk>/",
         CompanyInvoiceViewSet.as_view({"put": "update", "delete": "destroy", "get": "retrieve",
                                        "patch": "partial_update"}),
         name="invoice-memo-detail"),
    path("job/<int:job_id>/wrap_job/",
         CompanyInvoiceViewSet.as_view({"post": "wrap_job"}),
         name="invoice-memo"),
    path("job/<int:job_id>/archive_job/",
         CompanyInvoiceViewSet.as_view({"post": "archive_job"}),
         name="archive-job"),
    path("job/<int:job_id>/contractor_deal_memos/",
         CompanyInvoiceViewSet.as_view({"get": "retrieve_contractor_deal_memos_in_a_job"}),
         name="retrieve-contractor-deal-memos-in-a-job"),
    path("job/<int:job_id>/contractor_invoices/",
         CompanyInvoiceViewSet.as_view({"get": "retrieve_contractor_invoices_in_a_job"}),
         name="retrieve-contractor-invoices-in-a-job"),
    path("job/<int:job_id>/invoice_memos/",
         CompanyInvoiceViewSet.as_view({"get": "retrieve_invoice_memos_in_a_job"}),
         name="retrieve-invoice-memos-in-a-job"),
    path("job/<int:job_id>/job_memo/<int:invoice_memo_id>/invoice/",
         CompanyInvoiceViewSet.as_view({"get": "get_invoice"}),
         name="get-invoice"),
    path("job/<int:job_id>/invoice/<int:invoice_id>/process/",
         CompanyInvoiceViewSet.as_view({"post": "process_invoice"}),
         name="process-invoice"),
    path("job/<int:job_id>/invoice/<int:invoice_id>/dispute/",
         CompanyInvoiceViewSet.as_view({"patch": "mark_as_disputed"}),
         name="process-invoice"),
    path("job/<int:job_id>/invoice/<int:invoice_id>/approve/",
         CompanyInvoiceViewSet.as_view({"patch": "approve"}),
         name="process-invoice"),
    path("job/<int:job_id>/pay_invoices/",
         CompanyInvoiceViewSet.as_view({"post": "pay_invoices"}),
         name="pay-invoices"),
    # Contractor Finance
    path("user/<int:user_id>/finance/invoices/",
         ContractorInvoiceViewSet.as_view({"get": "get_contractor_invoices"}),
         name="get-finance-contractor-invoices"),
    path("user/<int:user_id>/finance/statistics/",
         ContractorInvoiceViewSet.as_view({"get": "get_contractor_statistics"}),
         name="get-contractor-statistics"),
    path("user/<int:user_id>/invoice/<int:invoice_id>/update_invoice_number/",
         ContractorInvoiceViewSet.as_view({"post": "update_invoice_number"}),
         name="update-invoice-number"),
    path("user/<int:user_id>/invoice/<int:invoice_id>/",
         ContractorInvoiceViewSet.as_view({"get": "get_contractor_invoice"}),
         name="get-contractor-invoice"),
    path("invoice/<int:pk>/",
         ContractorInvoiceViewSet.as_view({"patch": "partial_update", "delete": "destroy", "get": "retrieve"}),
         name="invoice-detail"),
    path("user/<int:user_id>/invoice/<int:invoice_id>/send_invoice/",
         ContractorInvoiceViewSet.as_view({"post": "send_invoice"}),
         name="send-invoice"),
    path("user/<int:user_id>/invoice/<int:invoice_id>/receipt/",
         InvoiceReceiptViewSet.as_view({"post": "create"}),
         name="invoice-receipt"),
    path("invoice_receipt/<int:pk>/",
         InvoiceReceiptViewSet.as_view({"put": "update", "delete": "destroy", "get": "retrieve",
                                        "patch": "partial_update"}),
         name="invoice-receipt-detail"),
    path("user/<int:user_id>/invoice/<int:invoice_id>/line_item/",
         InvoiceLineItemViewSet.as_view({"post": "create"}),
         name="invoice-line-item"),
    path("invoice_line_item/<int:pk>/",
         InvoiceLineItemViewSet.as_view({"put": "update", "delete": "destroy", "get": "retrieve",
                                        "patch": "partial_update"}),
         name="invoice-line-item-detail"),
    path("user/<int:user_id>/invoice/<int:invoice_id>/document/",
         InvoiceDocumentViewSet.as_view({"post": "create"}),
         name="invoice-document"),
    path("invoice_document/<int:pk>/",
         InvoiceDocumentViewSet.as_view({"put": "update", "delete": "destroy", "get": "retrieve",
                                        "patch": "partial_update"}),
         name="invoice-document-detail"),
    path("invoice_bill_from/<int:pk>/",
         InvoiceBillFromViewSet.as_view({"patch": "partial_update"}),
         name="invoice-bill-from-detail"),
    path("invoice_bill_to/<int:pk>/",
         InvoiceBillToViewSet.as_view({"patch": "partial_update"}),
         name="invoice-bill-to-detail"),
    path("user/invoice/",
         InvoiceViewSet.as_view({"post": "create"}),
         name="create-new-invoice"),
    path("job/report-preview/<int:job_id>/",
         PreviewReport.as_view({"post": "get_crew_info"}),
         name="report-preview"),
    path("job/report-preview/<int:job_id>/download/",
         PreviewReport.as_view({"post": "download_report"}),
         name="download-report"),
    path("job/<int:pk>/wrap_and_pay/",
         PreviewReport.as_view({"put": "update_payment_option"}),
         name="wrap-and-pay"),
    path("job/<int:job_id>/pay_approved/",
         PayFromBuddi.as_view({"get": "get_approved"}),
         name="pay-approved-details"),
    path("job/<int:job_id>/pay_approved/buddi_pay",
         PayFromBuddi.as_view({"post": "create"}),
         name="pay-approved-buddi"),
    path("job/<int:job_id>/pay_approved/bank_pay",
         PayFromBank.as_view({"post": "bulk_create"}),
         name="pay-approved-bank"),

]

urlpatterns = [
    path("", include(v1_urlpatterns)),
]
