export const FETCH_JOB_PPB_SETTINGS_REQUEST = 'FETCH_JOB_PPB_SETTINGS_REQUEST';
export const FETCH_JOB_PPB_SETTINGS_SUCCESS = 'FETCH_JOB_PPB_SETTINGS_SUCCESS';
export const FETCH_JOB_PPB_SETTINGS_FAIL = 'FETCH_JOB_PPB_SETTINGS_FAIL';

export const SET_JOB_PPB_SETTINGS_REQUEST = 'SET_JOB_PPB_SETTINGS_REQUEST';
export const SET_JOB_PPB_SETTINGS_SUCCESS = 'SET_JOB_PPB_SETTINGS_SUCCESS';
export const SET_JOB_PPB_SETTINGS_FAIL = 'SET_JOB_PPB_SETTINGS_FAIL';

export const DELETE_JOB_PPB_PAGE_REQUEST = 'DELETE_JOB_PPB_PAGE_REQUEST';
export const DELETE_JOB_PPB_PAGE_SUCCESS = 'DELETE_JOB_PPB_PAGE_SUCCESS';
export const DELETE_JOB_PPB_PAGE_FAIL = 'DELETE_JOB_PPB_PAGE_FAIL';

export const FETCH_JOB_PPB_CONTENT_REQUEST = 'FETCH_JOB_PPB_CONTENT_REQUEST';
export const FETCH_JOB_PPB_CONTENT_SUCCESS = 'FETCH_JOB_PPB_CONTENT_SUCCESS';
export const FETCH_JOB_PPB_CONTENT_FAIL = 'FETCH_JOB_PPB_CONTENT_FAIL';

export const UPDATE_JOB_PPB_PAGE_REQUEST = 'UPDATE_JOB_PPB_PAGE_REQUEST';
export const UPDATE_JOB_PPB_PAGE_SUCCESS = 'UPDATE_JOB_PPB_PAGE_SUCCESS';
export const UPDATE_JOB_PPB_PAGE_FAIL = 'UPDATE_JOB_PPB_PAGE_FAIL';

export const SET_JOB_PPB_PAGE_ORDER_REQUEST = 'SET_JOB_PPB_PAGE_ORDER_REQUEST';
export const SET_JOB_PPB_PAGE_ORDER_SUCCESS = 'SET_JOB_PPB_PAGE_ORDER_SUCCESS';
export const SET_JOB_PPB_PAGE_ORDER_FAIL = 'SET_JOB_PPB_PAGE_ORDER_FAIL';

export const UPDATE_JOB_PPB_WATERMARK_REQUEST = 'UPDATE_JOB_PPB_WATERMARK_REQUEST';
export const UPDATE_JOB_PPB_WATERMARK_SUCCESS = 'UPDATE_JOB_PPB_WATERMARK_SUCCESS';
export const UPDATE_JOB_PPB_WATERMARK_FAIL = 'UPDATE_JOB_PPB_WATERMARK_FAIL';

export const SET_JOB_PPB_TEXT_STYLE = 'SET_JOB_PPB_TEXT_STYLE';

export const RESET_JOB_PPB_TEXT_STYLE_REQUEST = 'RESET_JOB_PPB_TEXT_STYLE_REQUEST';
export const RESET_JOB_PPB_TEXT_STYLE_SUCCESS = 'RESET_JOB_PPB_TEXT_STYLE_SUCCESS';
export const RESET_JOB_PPB_TEXT_STYLE_FAIL = 'RESET_JOB_PPB_TEXT_STYLE_FAIL';
