const UserTypes = {
  EXECUTIVE_PRODUCER: ['OWNER', 'PRIVILEGED STAFF'],
  PRODUCER: ['OWNER', 'PRIVILEGED STAFF', 'COMMON STAFF'],
  CONTRACTOR: ['CONTRACTOR'],
  AGENCY: [],
  BRAND: []
};

export default UserTypes;